"""
EventType enumeration.

Defines all platform domain event types.
"""

from enum import Enum


class EventType(str, Enum):
    """
    Categorical enumeration of all domain event types across the Mali Runanubandh platform.
    """
    # Community events
    POST_CREATED = "POST_CREATED"
    POST_SUBMITTED = "POST_SUBMITTED"
    POST_NEEDS_CHANGES = "POST_NEEDS_CHANGES"
    POST_RESUBMITTED = "POST_RESUBMITTED"
    POST_UPDATED = "POST_UPDATED"
    POST_APPROVED = "POST_APPROVED"
    POST_REJECTED = "POST_REJECTED"
    POST_DELETED = "POST_DELETED"
    COMMENT_CREATED = "COMMENT_CREATED"
    COMMENT_UPDATED = "COMMENT_UPDATED"
    COMMENT_DELETED = "COMMENT_DELETED"
    BIRTHDAY_WISH_CREATED = "BIRTHDAY_WISH_CREATED"
    POST_LIKED = "POST_LIKED"
    POST_UNLIKED = "POST_UNLIKED"
    POLL_VOTED = "POLL_VOTED"
    POST_REPORTED = "POST_REPORTED"
    HELP_REQUEST_CREATED = "HELP_REQUEST_CREATED"
    SUCCESS_STORY_CREATED = "SUCCESS_STORY_CREATED"
    ANNOUNCEMENT_PUBLISHED = "ANNOUNCEMENT_PUBLISHED"
    MARRIAGE_SUCCESS_CREATED = "MARRIAGE_SUCCESS_CREATED"

    # Future events placeholders
    USER_REGISTERED = "USER_REGISTERED"
    PROFILE_CREATED = "PROFILE_CREATED"
    PROFILE_UPDATED = "PROFILE_UPDATED"
    PROFILE_VERIFIED = "PROFILE_VERIFIED"
    PROPOSAL_SENT = "PROPOSAL_SENT"
    PROPOSAL_ACCEPTED = "PROPOSAL_ACCEPTED"
    PROPOSAL_REJECTED = "PROPOSAL_REJECTED"
    CHAT_STARTED = "CHAT_STARTED"
    MESSAGE_SENT = "MESSAGE_SENT"
    PAYMENT_COMPLETED = "PAYMENT_COMPLETED"
    SUBSCRIPTION_ACTIVATED = "SUBSCRIPTION_ACTIVATED"
